data = [{
        id: 1,
        image: "g2.jpg",
        name: "Em Bé",
        author: "Amee & Karik",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/EmBe-AMEEKarik-6719970.mp3",
    },
    {
        id: 2,
        image: "g3.jpg",
        name: "Đom Đóm",
        author: "Jack & G5R",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/DomDomLeMonRemix-JackG5R-6898454.mp3",
    },
    {
        id: 3,
        image: "g4.jpg",
        name: "Để Mị Nói Cho Mà Nghe",
        author: "Hoàng Thùy Linh",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/DeMiNoiChoMaNghe-HoangThuyLinh-6153588.mp3",
    },
    {
        id: 4,
        image: "g5.jpg",
        name: "Tình Yêu Xanh Mượt",
        author: "Đỗ Hoàng Dương",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/TinhYeuXanhMuotOstEmLaChangTraiCuaAnh-DoHoangDuongCodyUni5-6974163.mp3",
    },
    {
        id: 5,
        image: "g6.jpg",
        name: "Chàng Trai Sơ Mi Hồng",
        author: "Hoàng Duyên",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/ChangTraiSoMiHongOrinnRemix-HoangDuyen-6976919.mp3",
    },
    {
        id: 6,
        image: "g7.jpg",
        name: "Lấy Chồng Sớm Làm Gì",
        author: "HuyR & TuấnCry",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/LayChongSomLamGi-HuyRTuanCry-6175716.mp3",
    },
    {
        id: 7,
        image: "g8.jpg",
        name: "Lỡ Say Bye Là Bye",
        author: "Lemese & Changg",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/LoSayByeLaBye-LemeseChangg-6926941.mp3",
    },
    {
        id: 8,
        image: "g9.jpg",
        name: "Hành Lang Cũ",
        author: "Long Nón Lá & Masew",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/Hanh-Lang-Cu-Ha-Nho-Long-Non-La-Masew.mp3",
    },
    {
        id: 9,
        image: "g10.jpg",
        name: "Vô Duyên",
        author: "Suzie Nguyễn & Dra",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/VoDuyenSon2MRemix-SuzieNguyenDrA-5986770.mp3",
    },
    {
        id: 10,
        image: "g11.jpg",
        name: "Laylalay",
        author: "Jack & G5R",
        lyrics: [],
        type: "nhactre",
        link_ms: "sounds/Laylalay-JackG5R-7003742.mp3",
    },
    {
        id: 11,
        image: "n1.jpg",
        name: "Tiếng Đàn Kìm",
        author: "Thảo Vy",
        lyrics: [],
        type: "nhacbolero",
        link_ms: "sounds/TiengDanKim-ThaoVyTruTinh-7021575.mp3",
    },
    {
        id: 12,
        image: "n2.jpg",
        name: "Bậu ơi! Đừng Khóc",
        author: "Phi Nhung",
        lyrics: [],
        type: "nhacbolero",
        link_ms: "sounds/BauOiDungKhoc-PhiNhung-7014153.mp3",
    },
    {
        id: 13,
        image: "n3.jpg",
        name: "Bến Đợi Bơ Vơ",
        author: "Tố My",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/BenDoiBoVo-ToMy-7021872.mp3",
    },
    {
        id: 14,
        image: "n4.jpg",
        name: "Chiều Bên Đồi Sim",
        author: "Hoàng Hải",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/ChieuBenDoiSim-HoangHaiBolero-7006979.mp3",
    },
    {
        id: 15,
        image: "n5.jpg",
        name: "Đa Đa Bay Xa",
        author: "Bảo Nguyên",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/DaDaBayXa-BaoNguyen-7010145.mp3",
    },
    {
        id: 16,
        image: "n6.jpg",
        name: "Cố Quên Con Đò",
        author: "Khánh Bình",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/CoQuenConDo-KhanhBinh-7004586.mp3",
    },
    {
        id: 17,
        image: "n7.jpg",
        name: "Sương Trắng Miền Quê Ngoại",
        author: "Khánh Bình",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/SuongTrangMienQueNgoai-KhanhBinh-7004595.mp3",
    },
    {
        id: 18,
        image: "n8.jpg",
        name: "Bên Đục Bên Trong",
        author: "Cường Singer",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/BenDucBenTrong-NguyenCuongSinger-6995461.mp3",
    },
    {
        id: 19,
        image: "n9.jpg",
        name: "Đời Công Nhân",
        author: "Lư Thanh Tú",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/DoiCongNhan-LuThanhTu-6996022_hq.mp3",
    },
    {
        id: 20,
        image: "n10.jpg",
        name: "Mùa Hoa Bỏ Lại",
        author: "Lưu Triệu Vũ",
        lyrics: [

        ],
        type: "nhacbolero",
        link_ms: "sounds/MuaHoaBoLai-DuongTrieuVu-6995165.mp3",
    },
    {
        id: 41,
        image: "j1.jpg",
        name: "Sweet but Psycho",
        author: "Ava Max",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Sweet But Psycho - Ava Max.mp3",
    },
    {
        id: 42,
        image: "i2.jpg",
        name: "Pretty girl",
        author: "Maggie Lindemann",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Pretty Girl - Maggie Lindemann.mp3",
    },
    {
        id: 43,
        image: "i3.jpg",
        name: "Try",
        author: "Colbie Caillat",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Try - Colbie Caillat.mp3",
    },
    {
        id: 44,
        image: "i4.jpg",
        name: "Waiting For Love",
        author: "Avicii",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Waiting For Love - Avicii_ Simon Aldred.mp3",
    },
    {
        id: 45,
        image: "i5.jpg",
        name: "Death Bed",
        author: "Powfu",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/deathbed-Powfubeabadoobee-6233223.mp3",
    },
    {
        id: 46,
        image: "i6.jpg",
        name: "Mang Chủng",
        author: "Âm Khuyết Thi Thính",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/MangChung-TrieuPhuongTinhAmKhuyetThiThinh-5989054.mp3",
    },
    {
        id: 47,
        image: "i7.jpg",
        name: "Way Back Home",
        author: "Shaun",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Way Back Home - Shaun.mp3",
    },
    {
        id: 48,
        image: "i8.jpg",
        name: "Until You",
        author: "Shayne Ward",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Until You - Shayne Ward.mp3",
    },
    {
        id: 49,
        image: "i9.jpg",
        name: "Without Me",
        author: "Halsey",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Without Me - Halsey_ Juice WRLD.mp3",
    },
    {
        id: 50,
        image: "i10.jpg",
        name: "Hold On",
        author: "Chord Dverstreet",
        lyrics: [],
        type: "nhacnn",
        link_ms: "sounds/Hold On - Chord Overstreet.mp3",
    },
]